### ISSUE TITLE
8080 mnemonics?

### ISSUE THREAD

**Issue by xlar54** [ForNextSoftwareDevelopment/Z80_RC2014#1]
This is ideal for a project im working on, but the only issue is that it is for Z80 mnemonics...by chance could you add 8080 mnemonic support?

**Comment by ForNextSoftwareDevelopment** [comment]
Hi Scott,
That is possible but I already made a 8085 assembler/debugger, so what would be the added value of this ?
What is your project ?

**Comment by ForNextSoftwareDevelopment** [comment]
Unfortunately nothing heard from you (also not by the email I send so I'm closing this issue.
